[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_world = "FnTmCmzADAeEcc1gy9RtfTqw8HcP1hbpyGY5E6PZiiKW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
