services:
  subnet:
    # platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.builder
      target: subnet
    ports:
      - 9650:9650

  dev:
    # platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.builder
      target: dev
    stdin_open: true  # Keep STDIN open even if not attached
    tty: true  # Allocate a pseudo-TTY
      

