[features]
seeds = false
skip-lint = false
[programs.localnet]
multicontract_fib = "DAbhT2n9iSe5BsaRcT9HhGuRSGB8rkySfnJWLdsJWo65"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
