name: AWS Amplify Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      S3_BUCKET_NAME: your-bucket-name

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Upload content to AWS S3
        run: aws s3 sync book/html s3://movement-hack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
